<section class="mt 3 card caard-body">
    <h1>Gerenciar Alunos</h1>

    <div class="mt-2">
        <a href="/alunos/novo" class="btn btn-outline-dark">Novo Aluno</a>
    </div>
    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Matriculas</th>
                <th>CPF</th>
                <th>Email</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    
</section>