<section class="mt 3 card caard-body">
    <h1>Gerenciar Professores</h1>

    <div class="mt-2">
        <a href="/professor/novo" class="btn btn-outline-dark">Novo Professor</a>
    </div>
    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Endereço</th>
                <th>Formação</th>
                <th>CPF</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach ($professores as $professor) {
                    echo "
                        <tr>
                            <td>{$professor->id}</td>
                            <td>{$professor->nome}</td>
                            <td>{$professor->endereco}</td>
                            <td>{$professor->formacao}</td>
                            <td>{$professor->cpf}</td>
                    ";
                }
            ?>
        </tbody>
    </table>
    
</section>