<nav class="mt-3 d-flex justify-content-between">
    <div class="text-start">
        <a href="/" class="btn btn-outline-dark">Inicio</a>

        <a href="/alunos/listar" class="btn btn-outline-dark">Alunos</a>

        <a href="/professores/listar" class="btn btn-outline-dark">Professor</a>

        <a href="/cursos/listar" class="btn btn-outline-dark">Cursos</a>
    </div>
    
    <div class="text-end">
        <a href="/logout" class="btn btn-outline-danger">Desconectar</a>
    </div>
</nav>